"use client";

import * as React from "react";
import { CalendarDays, Download, Plane, Plus, Search, X } from "lucide-react";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { flights, flightFilters, type Flight, type FlightFilter, statusClasses } from "./flights-data";

function StatusBadge({ status }: { status: Flight["status"] }) {
  return <Badge variant="outline" className={statusClasses[status]}><span className="size-1.5 rounded-full bg-current" />{status}</Badge>;
}

function FlightDetails({ flight }: { flight: Flight }) {
  return <div className="flex h-full flex-col overflow-auto p-5">
    <div className="flex items-start justify-between gap-4"><div className="flex items-center gap-3"><div className="grid size-11 place-items-center rounded-xl bg-primary text-primary-foreground font-semibold">{flight.airlineCode}</div><div><h2 className="font-semibold text-lg">{flight.flightNumber}</h2><p className="text-sm text-muted-foreground">{flight.airline}</p></div></div><StatusBadge status={flight.status} /></div>
    <div className="my-6 rounded-2xl bg-muted/50 p-5"><div className="flex items-center justify-between"><div><div className="text-3xl font-semibold tracking-tight">{flight.origin.code}</div><div className="text-sm text-muted-foreground">{flight.origin.city}</div><div className="mt-4 text-sm font-medium">{flight.departure}</div></div><div className="flex flex-1 flex-col items-center px-4"><div className="text-xs text-muted-foreground">{flight.duration}</div><div className="my-2 flex w-full items-center gap-2"><div className="h-px flex-1 bg-border" /><Plane className="size-4 text-primary" /><div className="h-px flex-1 bg-border" /></div><div className="text-xs text-muted-foreground">{flight.date}</div></div><div className="text-right"><div className="text-3xl font-semibold tracking-tight">{flight.destination.code}</div><div className="text-sm text-muted-foreground">{flight.destination.city}</div><div className="mt-4 text-sm font-medium">{flight.arrival}</div></div></div></div>
    <Tabs defaultValue="overview" className="flex-1"><TabsList className="w-full justify-start"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="passengers">Passengers</TabsTrigger><TabsTrigger value="bookings">Bookings</TabsTrigger><TabsTrigger value="history">History</TabsTrigger></TabsList><TabsContent value="overview" className="mt-5"><div className="grid grid-cols-2 gap-4">{[["Gate",flight.gate],["Terminal",flight.terminal],["Aircraft",flight.aircraft],["Seats",`${flight.availableSeats} / ${flight.totalSeats}`],["Booked",`${flight.passengers} passengers`],["Last update",flight.lastUpdate]].map(([label,value])=><div key={label} className="rounded-xl border p-3"><div className="text-xs text-muted-foreground">{label}</div><div className="mt-1 text-sm font-medium">{value}</div></div>)}</div></TabsContent><TabsContent value="passengers" className="mt-5 text-sm text-muted-foreground">{flight.passengers} passengers are booked on this flight.</TabsContent><TabsContent value="bookings" className="mt-5 text-sm text-muted-foreground">Bookings connected to {flight.flightNumber} will appear here.</TabsContent><TabsContent value="history" className="mt-5 text-sm text-muted-foreground">{flight.lastUpdate}</TabsContent></Tabs>
    <div className="mt-6 flex gap-2"><Button className="flex-1">View Bookings</Button><Button variant="outline">Edit Flight</Button><Button variant="outline" size="icon" aria-label="Cancel flight"><X /></Button></div>
  </div>;
}

export function Flights() {
  const [filter, setFilter] = React.useState<FlightFilter>("All Flights"); const [query, setQuery] = React.useState(""); const [selected, setSelected] = React.useState(flights[0]); const [open, setOpen] = React.useState(false);
  const filtered = flights.filter((flight) => { const matchesQuery = `${flight.flightNumber} ${flight.airline} ${flight.origin.code} ${flight.destination.code}`.toLowerCase().includes(query.toLowerCase()); const matchesFilter = filter === "All Flights" || (filter === "Delayed" && flight.status === "Delayed") || (filter === "Cancelled" && flight.status === "Cancelled") || filter === "Departures" || filter === "Arrivals"; return matchesQuery && matchesFilter; });
  function select(flight: Flight) { setSelected(flight); if (window.innerWidth < 1024) setOpen(true); }
  return <div className="flex h-full min-h-0 flex-col gap-5 overflow-auto p-4 lg:p-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-sm text-muted-foreground">Operations / Schedule</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Flights</h1><p className="mt-1 text-sm text-muted-foreground">Manage flight schedules, routes, availability and operational status.</p></div><div className="flex gap-2"><Button variant="outline"><Download data-icon="inline-start" />Export</Button><Button><Plus data-icon="inline-start" />Add Flight</Button></div></header>
    <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-5"><Card className="xl:col-span-2 bg-primary text-primary-foreground"><CardHeader className="flex-row items-center justify-between pb-2"><CardTitle className="text-sm font-medium">Today&apos;s Flights</CardTitle><Plane className="size-4 opacity-70" /></CardHeader><CardContent><div className="text-3xl font-semibold">{flights.length}</div><p className="mt-1 text-xs opacity-75">4 departures · 1 arrival</p></CardContent></Card>{[["Upcoming Flights","12","Next 7 days"],["Delayed Flights","1","8.3% of schedule"],["Cancelled Flights","1","Updated 2h ago"],["Available Seats","240","68% capacity"]].map(([label,value,meta])=><Card key={label}><CardHeader className="pb-2"><CardTitle className="text-sm font-medium">{label}</CardTitle></CardHeader><CardContent><div className="text-2xl font-semibold">{value}</div><p className="mt-1 text-xs text-muted-foreground">{meta}</p></CardContent></Card>)}</div>
    <div className="flex flex-col gap-3"><div className="flex flex-col gap-3 lg:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search flight number, airline or route" className="pl-9" /></div><Button variant="outline"><CalendarDays data-icon="inline-start" />Today, Mar 18</Button><Select defaultValue="all"><SelectTrigger className="w-full lg:w-36"><SelectValue placeholder="Airline" /></SelectTrigger><SelectContent><SelectItem value="all">All airlines</SelectItem><SelectItem value="tk">Turkish Airlines</SelectItem><SelectItem value="pc">Pegasus</SelectItem></SelectContent></Select></div><div className="flex gap-1 overflow-x-auto rounded-lg bg-muted p-1">{flightFilters.map((item) => <Button key={item} variant={filter === item ? "default" : "ghost"} size="sm" onClick={() => setFilter(item)} className="shrink-0">{item}</Button>)}</div></div>
    <div className="grid min-h-0 gap-5 lg:grid-cols-[minmax(0,1fr)_380px]"><Card className="min-h-0 overflow-hidden"><CardHeader className="border-b py-4"><CardTitle className="text-base">Flight operations board <span className="ml-2 text-sm font-normal text-muted-foreground">{filtered.length} scheduled</span></CardTitle></CardHeader><CardContent className="p-0">{filtered.map((flight) => <button key={flight.id} onClick={() => select(flight)} className={`flex w-full flex-col gap-4 border-b p-4 text-left transition-colors hover:bg-muted/50 sm:grid sm:grid-cols-[150px_minmax(180px,1fr)_150px_120px] sm:items-center ${selected.id === flight.id ? "bg-muted/40" : ""}`}><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-lg bg-muted font-semibold text-xs">{flight.airlineCode}</div><div><div className="font-medium">{flight.flightNumber}</div><div className="text-xs text-muted-foreground">{flight.airline}</div></div></div><div><div className="flex items-center gap-3"><div><div className="font-semibold">{flight.origin.code}</div><div className="text-xs text-muted-foreground">{flight.departure}</div></div><div className="flex flex-1 items-center gap-2"><div className="h-px flex-1 bg-border" /><Plane className="size-3 text-primary" /><div className="h-px flex-1 bg-border" /></div><div className="text-right"><div className="font-semibold">{flight.destination.code}</div><div className="text-xs text-muted-foreground">{flight.arrival}</div></div></div><div className="mt-1 text-xs text-muted-foreground">{flight.origin.city} → {flight.destination.city} · {flight.duration}</div></div><div className="text-xs text-muted-foreground"><div>{flight.date}</div><div className="mt-1">Gate {flight.gate} · T{flight.terminal}</div></div><div className="flex items-center justify-between gap-2 sm:flex-col sm:items-end"><span className="text-xs text-muted-foreground">{flight.availableSeats} / {flight.totalSeats} seats</span><StatusBadge status={flight.status} /></div></button>)}</CardContent></Card><div className="hidden min-h-0 overflow-hidden rounded-xl border bg-card lg:block"><FlightDetails flight={selected} /></div></div>
    <Sheet open={open} onOpenChange={setOpen}><SheetContent side="right" className="w-full p-0 sm:max-w-xl"><SheetHeader className="sr-only"><SheetTitle>{selected.flightNumber} details</SheetTitle><SheetDescription>Flight operations and schedule details.</SheetDescription></SheetHeader><FlightDetails flight={selected} /></SheetContent></Sheet>
  </div>;
}

export default Flights;

